name: "RUN TESTS ON PUSH AND DEPLOY"
on:
  push:
    branches:
      - deployment
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set up npm
              uses: actions/setup-node@v1
              with:
                node-version: '18.x'
            - name: Install dependencies
              run: npm install
            - name: Run tests
              run: npm run test
            - name: Deploy to Amplify
              run: amplify publish --yes

